### ISSUE TITLE
SIFT-CLI can't upgrade

### ISSUE THREAD

**Issue by davidep** [sans-dfir/sift#260]
I'm having trouble on upgrading with SIFT-CLI. 
When I run the "sift upgrade" command it ends with some package installation failed (51). 
And each time I run the "sift upgrade" it always says that I'm still on sift V2017.48.0 
(this on happening on a SIFT workstation 16.04, also after upgrading to the latest *sift-cli 1.6.1*)

Below an example of errors that seemed related to pip, which has been already upgraded to last version.

```
# [INFO    ] Executing state pip.installed for [colorama]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [colorama] at time 13:23:54.888807 duration_in_ms=0.536
--
# [INFO    ] Executing state pip.installed for [construct]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [construct] at time 13:23:54.893645 duration_in_ms=1.111
--
# [INFO    ] Executing state pip.installed for [dpapick]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [dpapick] at time 13:23:54.906299 duration_in_ms=4.019
--
# [INFO    ] Executing state pip.installed for [distorm3]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [distorm3] at time 13:23:54.912469 duration_in_ms=1.307
--
# [INFO    ] Executing state pip.installed for [haystack]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [haystack] at time 13:23:54.917274 duration_in_ms=1.251
--
# [INFO    ] Executing state pip.installed for [lxml]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [lxml] at time 13:23:54.931336 duration_in_ms=0.993
--
# [INFO    ] Executing state pip.installed for [pefile]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [pefile] at time 13:23:54.939197 duration_in_ms=0.921
--
# [INFO    ] Executing state pip.installed for [pycoin]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [pycoin] at time 13:23:54.945568 duration_in_ms=2.314
--
# [INFO    ] Executing state pip.installed for [pysocks]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [pysocks] at time 13:23:54.951695 duration_in_ms=1.309
--
# [INFO    ] Executing state pip.installed for [simplejson]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [simplejson] at time 13:23:54.961793 duration_in_ms=1.242
--
# [INFO    ] Executing state pip.installed for [yara-python]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [yara-python] at time 13:23:54.966084 duration_in_ms=1.067
--
# [INFO    ] Executing state pip.installed for [git+https://github.com/dkovar/analyzeMFT.git@64c71d7c8905a119b7abdf9813e6ef5f11d3ccf1]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [git+https://github.com/dkovar/analyzeMFT.git@64c71d7c8905a119b7abdf9813e6ef5f11d3ccf1] at time 13:24:09.743554 duration_in_ms=1.012
--
# [INFO    ] Executing state pip.installed for [git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9] at time 13:24:09.746559 duration_in_ms=0.692
--
# [INFO    ] Executing state pip.installed for [argparse]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [argparse] at time 13:24:09.749585 duration_in_ms=0.775
--
# [INFO    ] Executing state pip.installed for [bitstring]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [bitstring] at time 13:24:09.753032 duration_in_ms=0.882
--
# [INFO    ] Executing state pip.installed for [docopt]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [docopt] at time 13:24:09.754213 duration_in_ms=0.989
--
# [INFO    ] Executing state pip.installed for [geoip2]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [geoip2] at time 13:24:09.757362 duration_in_ms=0.669
--
# [INFO    ] Executing state pip.installed for [machinae]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [machinae] at time 13:24:09.762408 duration_in_ms=0.765
--
# [INFO    ] Executing state pip.installed for [pip==9.0.1]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [pip==9.0.1] at time 13:24:09.765346 duration_in_ms=0.666
--
# [INFO    ] Executing state pip.installed for [python-dateutil >= 2.4.2]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [python-dateutil >= 2.4.2] at time 13:24:09.768506 duration_in_ms=0.714
--
# [INFO    ] Executing state pip.installed for [python-evtx]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [python-evtx] at time 13:24:09.780074 duration_in_ms=1.143
--
# [INFO    ] Executing state pip.installed for [python-magic]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [python-magic] at time 13:24:09.786002 duration_in_ms=1.448
--
# [INFO    ] Executing state pip.installed for [python-registry]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [python-registry] at time 13:24:09.789405 duration_in_ms=0.766
--
# [INFO    ] Executing state pip.installed for [setuptools]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [setuptools] at time 13:24:09.793586 duration_in_ms=0.898
--
# [INFO    ] Executing state pip.installed for [wheel]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [wheel] at time 13:24:09.810562 duration_in_ms=13.473
--
# [INFO    ] Executing state pip.installed for [six]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [six] at time 13:24:13.167729 duration_in_ms=1.088
--
# [INFO    ] Executing state pip.installed for [timesketch]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [timesketch] at time 13:24:13.189763 duration_in_ms=1.0
--
# [INFO    ] Executing state pip.installed for [unicodecsv]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [unicodecsv] at time 13:24:13.193973 duration_in_ms=0.957
--
# [INFO    ] Executing state pip.installed for [usnparser]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [usnparser] at time 13:24:13.198058 duration_in_ms=0.759
--
# [INFO    ] Executing state pip.installed for [virustotal-api]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [virustotal-api] at time 13:24:13.200345 duration_in_ms=0.661
--
# [INFO    ] Executing state pip.installed for [windowsprefetch]
# [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
# [INFO    ] Completed state [windowsprefetch] at time 13:24:13.203178 duration_in_ms=0.647
```

**Comment by ekristen** [comment]
There's a big problem with pip and pip 10 getting installed.

If you make sure you have the latest SIFT CLI 1.6.1 and then run `sudo sift upgrade` it should fix itself.

If that doesn't work, you can force pip to version 9.0.3 and try again.

**Comment by johnmccash** [comment]
I have this identical problem, but 'sudo sift upgrade' hasn't fixed it. How exactly would I go about forcing pip to 9.0.3? Also, a quick aside; This problem shouldn't have anything to do with being behind a proxy, should it?

**Comment by krisgelijkaan** [comment]
pip downgrade:

$ pip install pip==9.0.3


seems to help

**Comment by davidep** [comment]
Much better, although I still get 3 failures. 
And when I run it again after pip downgrade, it still starts from sift-version: v2017.48.0
Main issues are now on argparse and machinae
```
$ grep -C 1 -i error /var/cache/sift/cli/v2018.16.0/saltstack.log
You should consider upgrading via the 'pip install --upgrade pip' command.
# [INFO    ] There was no error installing package 'argparse' although it does not show when calling 'pip.freeze'.
# [INFO    ] Completed state [argparse] at time 09:59:51.325017 duration_in_ms=4666.908
--
# [DEBUG   ] Installed pip version: 9.0.3
# [ERROR   ] Error installing 'machinae': Could not find a `pip` binary
# [INFO    ] Completed state [machinae] at time 09:59:59.806797 duration_in_ms=5.448
--
    changes: {}
    comment: There was no error installing package 'argparse' although it does not
      show when calling 'pip.freeze'.
--
    changes: {}
    comment: 'Error installing ''machinae'': Could not find a `pip` binary'
    duration: 5.448
```

**Comment by johnmccash** [comment]
The errors that occur after downgrading to pip 9.0.3 (using 'pip install pip==9.0.3') seem to derive from the fact that there is no longer a /usr/bin/pip3 binary, which is required to install 'machinae', whatever that is. Is there a suggested pip command to work around this?

**Comment by johnmccash** [comment]
running "apt-get install python3-pip --reinstall" appears to have done the trick. Once that was done, "sift upgrade" seems to have run without errors. I'm now successfully upgraded to v2018.16.0.

**Comment by ekristen** [comment]
Thanks everyone for helping out. It is very much appreciated! I've opened #266 for tracking the python3-pip problem!
